image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @vue/cli@latest
  - npm install --progress=false

pages:
  stage: deploy
  script:
    - npm run build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 hrs
  only:
    - master